#!/bin/bash

rm -rf /root/limit-quota-xray >/dev/null 2>&1

clear
MYIP=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')

date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/MarocBeta/Permission/main/access"

clear
checking_sc() {
useexp=$(wget -qO- $data_ip | grep $MYIP | awk '{print $3}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
echo -e ""
echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
echo -e "   \033[0;33mYour VPS\033[0m $MYIP \033[0;33mHas been Banned\033[0m"
echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
echo -e "             \033[0;33mContact Admin :\033[0m"
echo -e "      \033[2;32mWhatsApp:\033[0m wa.me/212608607325"
echo -e "      \033[2;32mTelegram:\033[0m t.me/MarocBeta"
echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
exit 0
fi
}

checking_sc

function send-vmess-log(){
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<b>⚠️ XRAY VMESS QUOTA EXCEEDED ⚠️</b>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Remarks     : </code><code>$user</code>
<code>Limit Quota : </code><code>$total2</code>
<code>Usage Quota : </code><code>$total</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Account Automatically Deleted!</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
"
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function send-vless-log(){
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<b>⚠️ XRAY VLESS QUOTA EXCEEDED ⚠️</b>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Remarks     : </code><code>$user</code>
<code>Limit Quota : </code><code>$total2</code>
<code>Usage Quota : </code><code>$total</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Account Automatically Deleted!</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
"
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function send-trojan-log(){
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<b>⚠️ XRAY TROJAN QUOTA EXCEEDED ⚠️</b>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Remarks     : </code><code>$user</code>
<code>Limit Quota : </code><code>$total2</code>
<code>Usage Quota : </code><code>$total</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
<code>Account Automatically Deleted!</code>
<code>◇━━━━━━━━━━━━━━━━━━◇</code>
"
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function convert_bytes() {
    local bytes=$1
    local suffix=("B" "KB" "MB" "GB" "TB")
    local i=0
    while ((bytes >= 1024 && i < 4)); do
        bytes=$(( (bytes + 512) / 1024 ))
        ((i++))
    done
    echo "$bytes${suffix[i]}"
}

function vmq(){
while true; do
    sleep 15
    if [[ ! -e /etc/limit/vmess ]]; then
        mkdir -p /etc/limit/vmess
    fi
    
    data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" 2>/dev/null | grep -w "value" | awk '{print $2}' | cut -d '"' -f2)
        
        if [[ -z "$downlink" || "$downlink" == "0" ]]; then
            continue
        fi
        
        if [ -e /etc/limit/vmess/"${user}" ]; then
            plus2=$(cat /etc/limit/vmess/"${user}")
            if [[ ${plus2} -gt 0 ]]; then
                plus3=$(( ${downlink} + ${plus2} ))
                echo "${plus3}" > /etc/limit/vmess/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            else
                echo "${downlink}" > /etc/limit/vmess/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            fi
        else
            echo "${downlink}" > /etc/limit/vmess/"${user}"
            xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
    done
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        if [ -e /etc/vmess/"${user}" ]; then
            checkLimit=$(cat /etc/vmess/"${user}")
            if [[ ${checkLimit} -gt 1 ]]; then
                if [ -e /etc/limit/vmess/"${user}" ]; then
                    Usage=$(cat /etc/limit/vmess/"${user}")
                    if [[ -z "$Usage" ]]; then
                        continue
                    fi
                    
                    total=$(convert_bytes ${Usage})
                    total2=$(convert_bytes ${checkLimit})
                    if [[ ${Usage} -gt ${checkLimit} ]]; then
                        uuid=$(grep -E "###" "/etc/vmess/.vmess.db" | grep -wE "${user}" | awk '{print $4}' | uniq)
                        exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^### $user $exp/,/^},{/d" /etc/vmess/.vmess.db
                        send-vmess-log
                        rm -rf /etc/vmess/"${user}"
                        rm -rf /etc/limit/vmess/"${user}"
                        rm -rf /etc/rs/limit/vmess/ip
                        rm -rf /var/www/html/vmess-"${user}".html
                        systemctl restart xray > /dev/null 2>&1
                    fi
                fi
            fi
        fi
    done
done
}

function vlq(){
while true; do
    sleep 15
    if [[ ! -e /etc/limit/vless ]]; then
        mkdir -p /etc/limit/vless
    fi
    
    data=($(cat /etc/xray/config.json | grep '^#&' | cut -d ' ' -f 2 | sort | uniq))
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" 2>/dev/null | grep -w "value" | awk '{print $2}' | cut -d '"' -f2)
        
        if [[ -z "$downlink" || "$downlink" == "0" ]]; then
            continue
        fi
        
        if [ -e /etc/limit/vless/"${user}" ]; then
            plus2=$(cat /etc/limit/vless/"${user}")
            if [[ ${plus2} -gt 0 ]]; then
                plus3=$(( ${downlink} + ${plus2} ))
                echo "${plus3}" > /etc/limit/vless/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            else
                echo "${downlink}" > /etc/limit/vless/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            fi
        else
            echo "${downlink}" > /etc/limit/vless/"${user}"
            xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
    done
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        if [ -e /etc/vless/"${user}" ]; then
            checkLimit=$(cat /etc/vless/"${user}")
            if [[ ${checkLimit} -gt 1 ]]; then
                if [ -e /etc/limit/vless/"${user}" ]; then
                    Usage=$(cat /etc/limit/vless/"${user}")
                    if [[ -z "$Usage" ]]; then
                        continue
                    fi
                    
                    total=$(convert_bytes ${Usage})
                    total2=$(convert_bytes ${checkLimit})
                    if [[ ${Usage} -gt ${checkLimit} ]]; then
                        uuid=$(grep -E "#&" "/etc/vless/.vless.db" | grep -wE "${user}" | awk '{print $4}' | uniq)
                        exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^#& $user $exp/,/^},{/d" /etc/vless/.vless.db
                        send-vless-log
                        rm -rf /etc/vless/"${user}"
                        rm -rf /etc/limit/vless/"${user}"
                        rm -rf /etc/rs/limit/vless/ip
                        rm -rf /var/www/html/vless-"${user}".html
                        systemctl restart xray > /dev/null 2>&1
                    fi
                fi
            fi
        fi
    done
done
}

function trq(){
while true; do
    sleep 15
    if [[ ! -e /etc/limit/trojan ]]; then
        mkdir -p /etc/limit/trojan
    fi
    
    data=($(cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq))
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" 2>/dev/null | grep -w "value" | awk '{print $2}' | cut -d '"' -f2)
        
        if [[ -z "$downlink" || "$downlink" == "0" ]]; then
            continue
        fi
        
        if [ -e /etc/limit/trojan/"${user}" ]; then
            plus2=$(cat /etc/limit/trojan/"${user}")
            if [[ ${plus2} -gt 0 ]]; then
                plus3=$(( ${downlink} + ${plus2} ))
                echo "${plus3}" > /etc/limit/trojan/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            else
                echo "${downlink}" > /etc/limit/trojan/"${user}"
                xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
            fi
        else
            echo "${downlink}" > /etc/limit/trojan/"${user}"
            xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
    done
    
    for user in "${data[@]}"; do
        if [[ -z "$user" ]]; then
            continue
        fi
        
        if [ -e /etc/trojan/"${user}" ]; then
            checkLimit=$(cat /etc/trojan/"${user}")
            if [[ ${checkLimit} -gt 1 ]]; then
                if [ -e /etc/limit/trojan/"${user}" ]; then
                    Usage=$(cat /etc/limit/trojan/"${user}")
                    if [[ -z "$Usage" ]]; then
                        continue
                    fi
                    
                    total=$(convert_bytes ${Usage})
                    total2=$(convert_bytes ${checkLimit})
                    if [[ ${Usage} -gt ${checkLimit} ]]; then
                        uuid=$(grep -E "#!" "/etc/trojan/.trojan.db" | grep -wE "${user}" | awk '{print $4}' | uniq)
                        exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                        sed -i "/^#! $user $exp/,/^},{/d" /etc/trojan/.trojan.db
                        send-trojan-log
                        rm -rf /etc/trojan/"${user}"
                        rm -rf /etc/limit/trojan/"${user}"
                        rm -rf /etc/rs/limit/trojan/ip
                        rm -rf /var/www/html/trojan-"${user}".html
                        systemctl restart xray > /dev/null 2>&1
                    fi
                fi
            fi
        fi
    done
done
}

if [[ ${1} == "vmq" ]]; then
vmq
elif [[ ${1} == "vlq" ]]; then
vlq
elif [[ ${1} == "trq" ]]; then
trq
fi
